# Generated by Django 5.1.2 on 2024-11-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
