# Generated by Django 5.1.2 on 2024-11-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bio',
        ),
    ]
