# Generated by Django 5.1.2 on 2024-11-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_conversation_chat_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_message',
            name='room',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
