# Generated by Django 5.1.2 on 2024-11-12 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_my_notes_to_do'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_Notes',
            new_name='My_Note',
        ),
    ]
