# Generated by Django 5.1.2 on 2024-11-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar5.png', null=True, upload_to=''),
        ),
    ]
