# Generated by Django 5.1.2 on 2024-11-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_timing_alter_job_listing_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_listing',
            name='timing',
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
