# Generated by Django 5.1.2 on 2024-11-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash.timing'),
        ),
    ]
