# Generated by Django 5.1.2 on 2024-11-03 01:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.job_listing'),
            preserve_default=False,
        ),
    ]
