# Generated by Django 5.1.2 on 2024-11-03 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_feedback_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
