# Generated by Django 5.1.2 on 2024-11-03 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
