# Generated by Django 5.1.2 on 2024-11-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_job_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_proposal',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254),
        ),
    ]
