# Generated by Django 5.1.2 on 2024-11-07 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0018_job_listing_status_job_proposal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='tasker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_tasker', to=settings.AUTH_USER_MODEL),
        ),
    ]
