# Generated by Django 5.1.2 on 2024-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_job_listing_tasker'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_proposal',
            name='nature',
            field=models.CharField(default='Short Task', max_length=50),
        ),
    ]
