# Generated by Django 5.1.2 on 2024-11-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_job_proposal_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='featured_status',
            field=models.BooleanField(default=False),
        ),
    ]
