# Generated by Django 5.1.2 on 2024-11-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0021_job_listing_featured_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_proposal',
            name='email',
            field=models.EmailField(default='pluto@protonmail.com', max_length=254),
        ),
    ]
