# Generated by Django 5.1.2 on 2024-11-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0024_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_by',
            new_name='user',
        ),
    ]
