# Generated by Django 5.1.2 on 2024-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0026_note_type_notification_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
